using Chirp.Core;
using Chirp.Infrastructure;
using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;
namespace Chirp.Infrastructure.UnitTest;

public class AuthorRepositoryTest
{
    private readonly SqliteConnection _connection;
    private readonly DbContextOptions<ChirpDBContext> _contextOptions;

    public AuthorRepositoryTest()
    {
        _connection = new SqliteConnection("Filename=:memory:");
        _connection.Open();

        _contextOptions = new DbContextOptionsBuilder<ChirpDBContext>()
            .UseSqlite(_connection)
            .Options;

        var context = new ChirpDBContext(_contextOptions);
        context.Database.EnsureCreated();
    }
    
    [Fact]
    public void CreateAuthor_StoresNewAuthorInDbOrInDb_AssertAmountAuthors()
    {
        var context = new ChirpDBContext(_contextOptions);
        var authorRepository = new AuthorRepository(context);

        // Arrange
        var newAuthor = new Author
        {
            Name = "Name and",
            Email = "Email pair that isn't in the db",
        };

        // Act
        authorRepository.CreateAuthor(newAuthor);

        // Assert
        context.Authors.Should().HaveCount(1);
    }

    [Fact]
    public void CreatedAuthor_GetsAutogeneratedId_ShouldBeEquivalent()
    {
        var context = new ChirpDBContext(_contextOptions);
        var authorRepository = new AuthorRepository(context);

        // Arrange
        var authorsBefore = context.Authors.Count();

        var newAuthor = new Author
        {
            Name = "Hans Hansen", Email = "UniqueMail898989",
        };

        // Act
        authorRepository.CreateAuthor(newAuthor);

        // Assert
        var author = authorRepository.FindAuthorByName(newAuthor.Name);
        author.AuthorId.Should().NotBe(null);
        author.Name.Should().Be(newAuthor.Name);
        author.Email.Should().Be(newAuthor.Email);
    }

    [Fact]
    public void DeleteAuthor_RemovesAuthorFromDb()
    {
        var context = new ChirpDBContext(_contextOptions);
        var authorRepository = new AuthorRepository(context);

        // Arrange
        var author = new Author
        {
            Name = "Hans Hansen", Email = "UniqueMail898989", AuthorId = 1
        };
        var author2 = new Author
        {
            Name = "Hanne Hansen", Email = "UniqueMail898990", AuthorId = 2
        };

        context.Authors.Add(author);
        context.Authors.Add(author2);
        context.SaveChanges();

        // Act
        authorRepository.DeleteAuthor(author.Name);

        // Assert
        context.Authors.Should().ContainSingle(a => a.AuthorId == author2.AuthorId);
    }
}