using Chirp.Core;
using Chirp.Infrastructure;
using ChirpDBContext = Chirp.Infrastructure.ChirpDBContext;
using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;
namespace Chirp.Razor.UnitTest;

public class AuthorTest : IDisposable
{
    private readonly DbContextOptions<ChirpDBContext> _contextOptions;

    public AuthorTest()
    {

        _contextOptions = new DbContextOptionsBuilder<ChirpDBContext>()
            .UseInMemoryDatabase(databaseName: "ChirpDB")
            .EnableSensitiveDataLogging()
            .Options;

        using var context = new ChirpDBContext(_contextOptions);
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        context.Authors.AddRange(
            new Author { Name = "Jens", Email = "test@mail.dk" },
            new Author { Name = "Børge", Email = "wow@dd.dk" }
        );

        context.SaveChanges();
    }

    public void Dispose()
    {
        using var context = new ChirpDBContext(_contextOptions);
        context.Database.EnsureDeleted();
    }
    
    [Fact]
    public void CreateAuthor_StoresNewAuthorInDbOrInDb_AssertAmountAuthors()
    {
        using var context = new ChirpDBContext(_contextOptions);
        var authorRepository = new AuthorRepository(context);

        // Arrange
        foreach (var author in context.Authors)
        {
            Console.WriteLine(author.Name); 
        }
        var authorsBefore = context.Authors.Count();

        var newAuthor = new Author
        {
            Name = "Name and",
            Email = "Email pair that isn't in the db",
        };

        // Act
        authorRepository.CreateAuthor(newAuthor.Name, newAuthor.Email);

        // Assert
        context.Authors.Count().Should().Be(authorsBefore + 1);
    }

    [Fact]
    public void FindAuthorByName_ReturnsAListOfAuthors_ShouldHaveExpectedAuthors()
    {
        using var context = new ChirpDBContext(_contextOptions);
        var authorRepository = new AuthorRepository(context);

        // Arrange
        var authorsWithTheSameName = new List<Author>
        {
            new () { Name = "Ida", Email = "ida1@" },
            new () { Name = "Ida", Email = "ida2@" }
        };
        context.Authors.AddRange(authorsWithTheSameName);
        context.SaveChanges();

        // Act and Assert
        authorRepository.FindAuthorsByName("Ida").Should().BeEquivalentTo(authorsWithTheSameName);
    }

    [Fact]
    public void CreatedAuthor_GetsAutogeneratedId_ShouldBeEquivalent()
    {
        using var context = new ChirpDBContext(_contextOptions);
        var authorRepository = new AuthorRepository(context);

        // Arrange
        var authorsBefore = context.Authors.Count();

        var newAuthor = new Author
        {
            Name = "Hans Hansen", Email = "UniqueMail898989",
        };

        // Act
        authorRepository.CreateAuthor(newAuthor.Name, newAuthor.Email);

        // Assert
        var author = authorRepository.FindAuthorsByEmail(newAuthor.Email).First();
        author.AuthorId.Should().NotBe(null);
        author.Name.Should().Be(newAuthor.Name);
        author.Email.Should().Be(newAuthor.Email);
    }
}